context.objects = [
    { 
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = "ds-capture-sink"
            node.description = "DS Capture Card Sink"
            media.class = Audio/Sink
            audio.position = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
            adapter.auto-port-config = {
                mode = dsp
                monitor = true
                position = preserve
            }
        }
    }
        { 
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = "game-sink"
            node.description = "Game Capture Sink"
            media.class = Audio/Sink
            audio.position = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
            adapter.auto-port-config = {
                mode = dsp
                monitor = true
                position = preserve
            }
        }
    }
        { 
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = "bmg-sink"
            node.description = "Background Music Capture Sink"
            media.class = Audio/Sink
            audio.position = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
            adapter.auto-port-config = {
                mode = dsp
                monitor = true
                position = preserve
            }
        }
    }]


context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = game-sink
                node.description = "Game Audio Sink"
            }
            playback.props = {
                node.name = "game-sink.output"
                node.passive = true
                audio.position = [ FL FR ]
                target.object = "alsa_output.pci-0000_10_00.4.analog-stereo"
                node.description = "Game Audio Output"
                stream.dont-remix = true
            }
        }
    }
    {   name = libpipewire-module-loopback
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = bgm-sink
                node.description = "BGM Sink"
            }
            playback.props = {
                node.name = "bgm-sink.monitor"
                node.passive = true
                audio.position = [ FL FR ]
                target.object = "alsa_output.pci-0000_10_00.4.analog-stereo"
                node.description = "BGM Output"
                stream.dont-remix = true
            }
        }
    }
]
