context.modules = [   
    { 
        name = libpipewire-module-null-sink
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = bgm-sink
            }
        }
    }
    { 
        name = libpipewire-module-null-sink
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = game-sink
            }
        }
    }
    { 
        name = libpipewire-module-null-sink
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = ds-capture-sink
            }
        }
    }
]