access.rules = [
    {
        matches = [
            { application.process.binary = "chrome" },
            { application.process.binary = "chromium" },
            { application.process.binary = "discord" },
            { application.process.binary = "electron" },
            { application.process.binary = "firefox" },
            { application.process.binary = "vesktop" },
            { application.process.binary = "vesktop-bin" },
            { application.process.binary = "webcord" },
            { application.process.binary = "zoom" },
            { application.process.binary = "slack" },
            { application.process.binary = "fluxer" },
        ]
        actions = {
            update-props = {
                default_permissions = "rx"
            }
        }
    }
]